---
name: Config-Inetd
version: 0.30_01
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
abstract: Interface inetd's configuration file
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  Carp: 0
  Fcntl: 0
  Params::Validate: 0
  Tie::File: 0
  boolean: 0
configure_requires:
  Module::Build: 0.340201
provides:
  Config::Inetd:
    file: lib/Config/Inetd.pm
    version: 0.30_01
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
