---
abstract: "Interface inetd's configuration file"
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Inetd
provides:
  Config::Inetd:
    file: lib/Config/Inetd.pm
    version: 0.30_02
requires:
  Carp: 0
  Fcntl: 0
  Params::Validate: 0
  Tie::File: 0
  boolean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.30_02
