---
abstract: "Interface inetd's configuration file"
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-Inetd
provides:
  Config::Inetd:
    file: lib/Config/Inetd.pm
    version: '0.32'
requires:
  Carp: '0'
  Fcntl: '0'
  Params::Validate: '0'
  Tie::File: '0'
  boolean: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/stsc/Config-Inetd
version: '0.32'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
